In [105]:
import numpy as np
from scipy.linalg import null_space

In [106]:
# 初始化A矩阵
A = np.array([[2,4],[1,3],[0,0],[0,0]],dtype=float)
m,n = A.shape
np.set_printoptions(precision=4)

In [107]:
# 计算A的转置乘A，并求特征值、特征向量
ATA = np.array(A.T@A)
ATA_value,ATA_vector = np.linalg.eig(ATA)
print(ATA)

[[ 5. 11.]
 [11. 25.]]


In [108]:
# 对特征值按降序排序
argsort_value_index = np.argsort(-ATA_value)
ATA_sort_value = ATA_value[argsort_value_index]
# 按特征值降序排序特征向量作为V矩阵列向量并将其转置的VT矩阵
VT = ATA_vector[argsort_value_index]
print(f'VT:{VT}')
# 对特征值取根号获取奇异值
sigma_list = []
for i in range (0,ATA_sort_value.shape[0]):
    value = np.sqrt(ATA_sort_value[i])
    sigma_list.append(value)
print(f'奇异值：{sigma_list}')

VT:[[ 0.4046 -0.9145]
 [-0.9145 -0.4046]]
奇异值：[5.464985704219043, 0.3659661906262547]


In [109]:
# 构造m*n对角矩阵sigma_matrix
sigma_matrix = np.zeros((m,n))
sigma_matrix[:len(sigma_list),:len(sigma_list)] = np.diag(sigma_list)
print(f'对角矩阵：{sigma_matrix}')

对角矩阵：[[5.465 0.   ]
 [0.    0.366]
 [0.    0.   ]
 [0.    0.   ]]


In [110]:
# 计算U矩阵
U = np.zeros((m,m)) # 初始化U矩阵
for i in range(m):
    # 计算U1
    if i < len(sigma_list) and (sigma_list[i]>0):
        # i<=r时 计算u_j = 1/sigma_j*A*v_j
        uj = 1/sigma_list[i] * (A@ VT[i])
        U[i] = uj
    # 计算U2
    else:
         # i>r时 计算U2为A^T的零空间的标准正交基
        U2 = null_space(A.T).T
        for j in range(len(U2)):
            U[i] = U2[j]
        break
# 转置得到U矩阵
U= U.T
print(f'U:{U}')

U:[[-0.5213 -9.4196  0.      0.    ]
 [-0.428  -5.8152  0.      0.    ]
 [ 0.      0.      0.      0.    ]
 [ 0.      0.      1.      0.    ]]


In [111]:
A_res = U@sigma_matrix@VT
# 验证结果
print(f'U * Sigma * V^T :\n{A_res}')
print(f'A:\n{A}')   

U * Sigma * V^T :
[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]
A:
[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]


In [112]:
# 外积展开式
# A = sigma_1u_1v_1^T+sigma_2u2v_2^T
A_outer = sigma_list[0]*np.outer(U[:,0],VT[0,:])+sigma_list[1]*np.outer(U[:,1],VT[1,:])
print(f'A外积展开式计算结果:\n{A_outer}')

A外积展开式计算结果:
[[ 2.  4.]
 [ 1.  3.]
 [ 0. -0.]
 [ 0. -0.]]
