In [229]:
import numpy as np
from scipy.linalg import null_space

In [230]:
A = np.array([[2,4],[1,3],[0,0],[0,0],[0,0]])
# A =np.array([[4,0],[3,0],[0,0]])
m,n = A.shape
if m<n:
    A = A.conj().T
print(m,n)
print(A)

5 2
[[2 4]
 [1 3]
 [0 0]
 [0 0]
 [0 0]]


In [231]:
ATA = np.array(A.conj().T@A)
print(ATA)

[[ 5 11]
 [11 25]]


In [232]:
ATA_value,ATA_vector = np.linalg.eig(ATA)
print(ATA_vector)
print(ATA_value)


[[-0.9145143  -0.40455358]
 [ 0.40455358 -0.9145143 ]]
[ 0.13393125 29.86606875]


In [233]:
sigma_list = []
argsort_value = np.argsort(-ATA_value)
ATA_sort_value = ATA_value[argsort_value]
print(ATA_sort_value)
for i in range (0,ATA_sort_value.shape[0]):
    value = np.sqrt(ATA_sort_value[i])
    sigma_list.append(value)
    print(value)
print(sigma_list)

    

[29.86606875  0.13393125]
5.464985704219043
0.3659661906262547
[5.464985704219043, 0.3659661906262547]


In [234]:
sigma_matrix = np.zeros((m,n))
sigma_matrix[:len(sigma_list),:len(sigma_list)] = np.diag(sigma_list)
print(sigma_matrix)

[[5.4649857  0.        ]
 [0.         0.36596619]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]


In [235]:

VTMatrix = ATA_vector[argsort_value]
print(VTMatrix)

[[ 0.40455358 -0.9145143 ]
 [-0.9145143  -0.40455358]]


In [236]:
U = np.zeros((m,m))
b = np.zeros((1,n))
print(A.T)
for i in range(m):
    
    if i < len(sigma_list) and (sigma_list[i]>0):
        uj = 1/sigma_list[i] * (A@ VTMatrix[i])
        print(uj)
        U[i] = uj
    else:
        # mr,_ = np.linalg.qr(A.T)
        mr = np.linalg.lstsq(A.T,b.T,rcond=None)
        print(mr[0].T)
        U[i] = mr[0][0].T
        
print(U)

[[2 1 0 0 0]
 [4 3 0 0 0]]
[-0.52130969 -0.4279955   0.          0.          0.        ]
[-9.41956667 -5.81522311  0.          0.          0.        ]
[[0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]
[[-0.52130969 -0.4279955   0.          0.          0.        ]
 [-9.41956667 -5.81522311  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]


In [237]:
print(U.T@sigma_matrix@VTMatrix)

[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [238]:
AAT = A@A.conj().T
print(AAT)

[[20 14  0  0  0]
 [14 10  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [242]:
AAT_value,AAT_vector = np.linalg.eig(AAT)
print(AAT_vector)
AAT_value[AAT_value<1e-5] = 0
print(AAT_value)
argsort2_value = np.argsort(-AAT_value)
print(argsort2_value)

[[ 0.81741556 -0.57604844  0.          0.          0.        ]
 [ 0.57604844  0.81741556  0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [ 0.          0.          0.          0.          1.        ]]
[29.86606875  0.13393125  0.          0.          0.        ]
[0 1 2 3 4]


In [243]:
U= AAT_vector[argsort2_value]
print(U)

[[ 0.81741556 -0.57604844  0.          0.          0.        ]
 [ 0.57604844  0.81741556  0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [ 0.          0.          0.          0.          1.        ]]


In [244]:
print(U@sigma_matrix@VTMatrix)

[[ 2. -4.]
 [ 1. -3.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
